name: Create release
on:
  push:
    branches:
      - master

jobs:
  create-release:
    if: github.repository == 'zCloak-Network/zkid-credential'
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install deps
        run: |
          yarn install --immutable | grep -v 'YN0013'

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn zcloak-dev-bump-version
          publish: yarn release
          commit: "chore: Version App"
          title: "chore: Version App"
          createGithubReleases: false

